### ISSUE TITLE
file_rec/async not ignoring files in .gitignore using ag

### ISSUE THREAD

**Issue by nickell** [Shougo/unite.vim#1027] opened 2015-09-25 15:06 UTC
* Problem summary
 * The file_rec/async source is no longer ignoring files contained in .gitignore while using ag
 * I would think this was an `ag` issue but running `ag --follow --nocolor --nogroup --hidden -g ""` on the command line outputs the correct files

* Environment Information
 * OS: OS X 10.10.5
 * Vim version: 7.4.826

* Minimal vimrc less than 50 lines

```
set nocompatible
set runtimepath+=~/.vim/bundle/vimproc/
set runtimepath+=~/.vim/bundle/unite.vim/
let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup',  '--hidden', '-g', '']
```

* Reproducable ways from Vim starting

 1. startup vim in a git repo
 2. call :Unite file_rec/async
 3. search for files ignored by .gitignore

* Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/4211048/10103946/e53b7488-6374-11e5-82ae-7c3cd90a43f3.png)

**Comment by Shougo** [comment] 2015-09-25 23:43
I cannot reproduce the problem.
node_modules is ignored.
Please upload the .gitignore file and clear file_rec/async cache.

**Comment by nickell** [comment] 2015-09-26 15:30
I have cleared the cache by deleting everything in ~/.cache/unite and also by using <Plug>(unite_redraw) for good measure. And I am still having this issue. I have created an example repo with a .gitignore excluding 1.js. If you clone this repo and create a file called 1.js and then call :Unite file_rec, it will still show me 1.js.

Steps:
``` bash
git clone git@github.com:nickell/unite-issue.git
cd /path/to/unite-issue
touch 1.js
vim -u /path/to/unite-issue/.vimrc-unite-issue 2.js
# inside vim call :Unite file_rec
```

Also, I have the latest unite (6.2) and ag (0.31.0)

Thanks for your help with this, absolutely amazing plugin btw, I couldn't live without it.

**Comment by Shougo** [comment] 2015-09-28 10:39
OK.  I will test it later.

**Comment by Shougo** [comment] 2015-09-29 13:01
I cannot reproduce it using `:Unite file_rec/async`.  Closing.

> # inside vim call :Unite file_rec and see "1.js" in the listing

Please use `:Unite file_rec/async`.  `:Unite file_rec` does not use ag.

**Closed by Shougo** 2015-09-29 13:01 UTC

**Comment by ZedZhang** [comment] 2016-03-28 14:25
I found the same issue here. @nickell Did you find out the solution?

**Comment by nickell** [comment] 2016-03-28 14:29
No I never was able to get this working @ZedZhang. I eventually switched to Neovim and for Unite I'm using the file_rec/neovim source, hope that helps!

**Comment by ZedZhang** [comment] 2016-03-28 14:36
@nickell Thx a lot! I will take it a try.

**Comment by FrankFang** [comment] 2016-04-14 09:29
Same for me. node_modules makes searching very laggy.
