### ISSUE TITLE
complete miss something after type backsapece

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/unite.vim#1126] opened 2016-02-23 12:28 UTC
# Problems summary
type into `:Unite fi`  then type `backspace`and `tab`,should complete all the source name begin with `f` not only `fi`.

## Expected
even I type some char I do not want, then I use `backspace` delete it, after that complete should works well

## Environment Information
 * OS: ubuntu 15.10
 * Vim version: neovim latest version

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=/home/wsdjeg/.cache/vimfiles/unite.vim
```

## The reproduce ways from Vim starting (Required!)

 1. `:Unite fi`
 2.  `backspace`
 3.  `tab`

**Comment by chemzqm** [comment] 2016-02-23 12:45
Can't reproduced with latest neovim on my Mac.

**Comment by wsdjeg** [comment] 2016-02-23 12:54
@chemzqm any diff between
`:Unite f` `tab`
and
`:Unite fi` `backspace` `tab`

**Comment by wsdjeg** [comment] 2016-02-23 12:58
ok it is my fault,but I can not use `Unite f` complete `file_rec`

**Comment by Shougo** [comment] 2016-02-24 12:01
It is not unite issue.  Closing.

**Closed by Shougo** 2016-02-24 12:01 UTC

**Comment by wsdjeg** [comment] 2016-02-24 12:07
![2016-02-24 20-04-06](https://cloud.githubusercontent.com/assets/13142418/13284854/f818daca-db31-11e5-9d7b-0b1c98ae6322.png)
but it should be like this
![2016-02-24 20-04-52](https://cloud.githubusercontent.com/assets/13142418/13284864/16901662-db32-11e5-9b08-053ab3bf3166.png)

**Comment by Shougo** [comment] 2016-02-24 12:13
OK.  Fixed.

**Comment by wsdjeg** [comment] 2016-02-24 12:22
thanks for your work
