### ISSUE TITLE
source_grep seems to ignore max_candidates

### ISSUE THREAD

**Issue by Ram-Z** [Shougo/unite.vim#904] opened 2015-04-22 11:57 UTC
* Problems summary
Unable to set max_candidates for grep source. It seems to always return around 65 candidates.

* Expected
The number of candidates set in the option

* Environment Information
 * OS: Chakra Linux
 * Vim version: VIM - Vi IMproved 7.4 1-617

* Minimal vimrc less than 50 lines

```vim
set nocompatible
set runtimepath+=~/.local/share/vim/vimproc.vim
set runtimepath+=~/.local/share/vim/unite.vim

let g:unite_source_grep_max_candidates = 2000
" or
call unite#custom#source('grep', 'max_candidates', 0)

if executable('ag')
    let g:unite_source_grep_command = 'ag' 
    let g:unite_source_grep_default_opts = '--smart-case -w --vimgrep --hidden --ignore ''.hg'' --ignore  ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
    let g:unite_source_grep_recursive_opt = ''
end

nnoremap [unite] <Nop>
nmap <leader>u [unite]
nnoremap <silent> [unite]a :<C-u>Unite grep -input=<C-R><C-W><CR>
```

* Reproducable ways from Vim starting

 0. startup vim (make sure to have `ag` in `PATH`
 1. put cursor over word to search for in current dir. (make sure it exists more than around 60 times)
 2. type `<leader>ua`
 3. check number of elements in unite window

**Comment by Shougo** [comment] 2015-04-23 00:58
Please read the issue template.

https://github.com/Shougo/unite.vim/issues/584

I will check it.

**Comment by Ram-Z** [comment] 2015-04-23 02:22
Ah sorry about that... Updated

**Comment by Shougo** [comment] 2015-04-23 04:06
Unfortunatelly, I cannot reproduce the prblem.
Please update unite.vim and vimproc and rebuild vimproc.

**Comment by Shougo** [comment] 2015-04-23 04:06
Please upload scrrenshot.

**Comment by Ram-Z** [comment] 2015-04-23 14:54
Here is a screencast: https://rmz.io/unite.mkv

unite.vim and vimproc are uptodate.

**Comment by Shougo** [comment] 2015-04-24 07:15
OK.  But the problem is only reproduced in your environment.
So, I think it is not enough that your minimal .vimrc and reproduce ways.

* I don't have ag command same with your version.
So, please don't use ag in minimal .vimrc.

* And, please create same candidates example like this:
https://github.com/Shougo/unite.vim/issues/864

I will test it later.

**Comment by Ram-Z** [comment] 2015-04-24 12:19
`ag` is actually not needed, I can reproduce it with `grep` as well: https://rmz.io/unite2.mkv
```vim
set nocompatible
set runtimepath+=~/.local/share/vim/vimproc.vim
set runtimepath+=~/.local/share/vim/unite.vim

let g:unite_source_grep_max_candidates = 2000
" or
call unite#custom#source('grep', 'max_candidates', 0)
```

I don't understand what you mean with your second point.

**Comment by Shougo** [comment] 2015-04-26 07:29
> I don't understand what you mean with your second point.

Please create examples.

> put cursor over word to search for in current dir. (make sure it exists more than around 60 times)

I cannot reproduce it.

**Comment by Ram-Z** [comment] 2015-05-07 07:39
Sorry for the delay. Here are a few commands to set up an environment to reproduce this: (tested in zsh on linux, but should work in bash and OSX as well)

    cd $(mktemp -d)
    for i in $(seq 200); do; echo foo > $(mktemp -p .); done
    vim -u /path/to/vimrc
    # in vim
    :Unite grep:.::foo        # I get 85 results instead of 200
    :Unite grep -input=foo    # I get 170 results


>> put cursor over word to search for in current dir. (make sure it exists more than around 60 times)

> I cannot reproduce it.

This is not really important, it was related to the following mapping, which is not needed if you call `:Unite` directly.

    nnoremap <silent> [unite]a :<C-u>Unite grep -input=<C-R><C-W><CR>

**Comment by Shougo** [comment] 2015-05-07 08:07
I will test it.

**Comment by Shougo** [comment] 2015-05-07 08:14
> :Unite grep:.::foo        # I get 85 results instead of 200

I get 97 results.

> :Unite grep -input=foo    # I get 170 results

I get 170 results.

**Comment by bchretien** [comment] 2015-05-07 08:17
I also encountered this issue. With the `vimrc` provided here, `:Unite grep` with `.` or with the absolute path to the current directory did not return the same number of matches.  `let g:unite_source_grep_default_opts = '--vimgrep'` may also be enough for testing.

**Comment by Shougo** [comment] 2015-05-07 08:22
Yes, it reproduced.  It seems vimproc problem.  I will check it.

**Comment by Shougo** [comment] 2015-05-07 08:55
I created the vimproc issue.

**Comment by Shougo** [comment] 2015-05-14 01:31
It is fixed in latest vimproc version.  Closing.

**Closed by Shougo** 2015-05-14 01:31 UTC
Labels: Bug

**Comment by Shougo** [comment] 2015-08-20 11:59
Fixed.

**Comment by wanderer2** [comment] 2016-02-22 08:23
Hello Shougo. The issue reported by @bchretien still remains; i.e. `:Unite grep` with `.` or with the absolute path to the current directory does not return the same number of matches.

**Comment by Shougo** [comment] 2016-02-22 12:29
@wanderer2 Please create new issue using the issue template.
I will try it.

**Comment by wanderer2** [comment] 2016-02-22 19:32
Done. Thanks.
