### ISSUE TITLE
 Can't do grep with ag

### ISSUE THREAD

**Issue by elventear** [Shougo/unite.vim#1020] opened 2015-09-14 16:41 UTC
* Problems summary

Can't use `Unite grep` with `ag`, after I updated to the latest code. It used to work. I also updated to the latest `vimproc` code.

* Expected

Able to `grep` with `ag`.

* Environment Information

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 25 2015 23:07:01)
MacOS X (unix) version
Included patches: 1-729
Compiled by pepe@gealach
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X_UNIX  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/opt/local/include  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1
Linking: /usr/bin/clang   -L. -L/opt/local/lib -Wl,-headerpad_max_install_names   -L/opt/local/lib  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -o vim        -lncurses -liconv -lintl -framework Cocoa  -L/opt/local/lib -llua -L/opt/local/lib -Wl,-headerpad_max_install_names   -fstack-protector  -L/opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -u _PyMac_Error /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python  -L/opt/local/lib -ltcl8.6 -lz -framework CoreFoundation -lruby.1.9.1 -lobjc -L/opt/local/lib
```

* Minimal vimrc less than 50 lines

```
set nocompatible
set runtimepath+=~/.vim/bundle/vimproc.vim
set runtimepath+=~/.vim/bundle/unite.vim

" Use ag in unite grep source.
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
\ '-i --vimgrep --hidden --ignore ' .
\ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''
```

* How to reproduce

 0. startup vim (Write with option arguments if necessary).
 1. `:Unite grep`
 2. Search for any string
 3. Get error:
```
[grep] Pattern: test
[unite.vim] function <SNR>18_call_unite..unite#start..unite#start#standard..unite#candidates#_recache..<SNR>36_recache_candidates_loop..<SNR>36_get_source_can
didates..7..8..unite#util#read_lines..<SNR>33_read_lines..<SNR>33_read_pipes..<SNR>33_read..<SNR>33_vp_pipe_read, line 5
[unite.vim] Vim(let):E688: More targets than List items
[unite.vim] Error occurred in gath
```

**Comment by Shougo** [comment] 2015-09-14 22:13
I cannot reproduce the problem in your minimal .vimrc.
Did you compile latest vimproc?

**Comment by elventear** [comment] 2015-09-14 22:32
I recompiled and it works now. Thanks for the help.

**Comment by Shougo** [comment] 2015-09-15 13:46
OK.

**Comment by jkeylu** [comment] 2015-09-20 02:49
@Shougo 
I meet the same problem.
![2015-09-20 10 43 16](https://cloud.githubusercontent.com/assets/423045/9978969/7cf67088-5f84-11e5-9860-67f73445f21a.png)

In my project folder, there is a file "bootstrap.css.map"

[https://raw.githubusercontent.com/twbs/bootstrap/master/dist/css/bootstrap.css.map](https://raw.githubusercontent.com/twbs/bootstrap/master/dist/css/bootstrap.css.map)

When I search "console", it occured an error.

**Comment by Shougo** [comment] 2015-09-23 01:15
@jkeylu Please update vimproc and recompile it.

**Comment by jkeylu** [comment] 2015-09-24 02:33
@Shougo I have already updated vimproc to latest version and recomplied it, but it still occur the error.

**Comment by Shougo** [comment] 2015-09-25 11:35
Hm...  But I cannot reproduce it.
Please use "git bisect" for vimproc.

**Comment by jkeylu** [comment] 2015-09-25 14:36
```
ccd34934748fc95917d4b63c9b2163ebcbd17e8e is the first bad commit
commit ccd34934748fc95917d4b63c9b2163ebcbd17e8e
Author: K.Takata <kentkt@csc.jp>
Date:   Wed Aug 26 00:59:21 2015 +0900

    Use new data format

    Each value consists of DataSize, Data, and EOV. DataSize is a 32-bit
    integer encoded into a 5-byte string.

    This data format can contain all binary data except NUL byte.
    Parsing might be faster than the old format.

    Related: #202, #204

:040000 040000 2b4dc7d2567364489a9b3f7ea245ff44a37d563e 267bc0270fa313a2a66d46d7227878b721478db0 M	autoload
```

**Comment by Shougo** [comment] 2015-09-25 23:05
@jkeylu other vimproc functions works in latest vimproc?
Please test it like `vimproc#system('ls')`.

**Comment by Shougo** [comment] 2015-09-25 23:08
@jkeylu Please provide detailed your environment information.

**Comment by jkeylu** [comment] 2015-09-26 02:29
* OS: OS X 10.10.5
* ag: `brew install the_silver_searcher`

```
the_silver_searcher: stable 0.31.0 (bottled), HEAD
Code-search similar to ack
https://github.com/ggreer/the_silver_searcher
/usr/local/Cellar/the_silver_searcher/0.30.0 (8 files, 116K)
  Poured from bottle
/usr/local/Cellar/the_silver_searcher/0.31.0 (8 files, 116K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/the_silver_searcher.rb
==> Dependencies
Build: autoconf ✘, automake ✘, pkg-config ✘
Required: pcre ✔, xz ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```

* Vim: `brew install vim --with-lua`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 11 2015 11:02:40)
MacOS X (unix) version
Included patches: 1-865
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```

* vimrc

```
set nocompatible
set runtimepath+=~/.vim/bundle/vimproc.vim
set runtimepath+=~/.vim/bundle/unite.vim

" Use ag in unite grep source.
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
\ '-i --vimgrep --hidden --ignore ' .
\ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_grep_recursive_opt = ''

nmap <silent> <S-f> :Unite -no-quit grep<CR>
```

* there are two files in my folder "README.md" and "bootstrap.css.map"

* `echo vimproc#system('cat README.md')`

![2015-09-26 10 26 06](https://cloud.githubusercontent.com/assets/423045/10115419/14f024d4-6439-11e5-9d2e-2a3257b2d3b2.png)

* `echo vimproc#system('ls')`

![2015-09-26 10 22 19](https://cloud.githubusercontent.com/assets/423045/10115407/8bba8ea2-6438-11e5-8f56-e0b84cc9fe97.png)

* `echo vimproc#system('ag -i --vimgrep --literal --hidden --ignore ''.git'' ''hello''')`

![2015-09-26 10 23 22](https://cloud.githubusercontent.com/assets/423045/10115410/af3847e8-6438-11e5-8756-3589adc8c181.png)

* `echo vimproc#system('ag -i --vimgrep --literal --hidden --ignore ''.git'' ''a''')`

![2015-09-26 10 17 02](https://cloud.githubusercontent.com/assets/423045/10115391/cdfba266-6437-11e5-9caa-dedfeb915f89.png)

**Comment by Shougo** [comment] 2015-09-26 11:06
It seems MacOS X environment bug.

**Comment by Shougo** [comment] 2015-09-26 11:10
@jkeylu Please update vimproc and test following command.

`:echo vimproc#system('echo -n ""')`

**Comment by jkeylu** [comment] 2015-09-26 12:00
* `:echo vimproc#system('echo -n ""')`

nothing

* `echo vimproc#system('ag -i --vimgrep --literal --hidden --ignore ''.git'' ''a''')`

![2015-09-26 19 52 14](https://cloud.githubusercontent.com/assets/423045/10117395/325a043c-6488-11e5-9735-6ccc93e4c17a.png)

**Comment by Shougo** [comment] 2015-09-26 12:18
@others Can you test the problem?   We need more testers.

**Comment by ainformatico** [comment] 2015-09-28 08:38
Having the same issue, also getting the same output as @jkeylu when running those commands.

**Comment by Shougo** [comment] 2015-09-28 10:56
OK.  I reproduced the problem.  It is fatal problem.

**Comment by Shougo** [comment] 2015-09-28 11:10
It is fixed in latest vimproc.
Please update it.

**Closed by Shougo** 2015-09-28 11:10 UTC

**Comment by ainformatico** [comment] 2015-09-28 11:13
Just updated, seems to work fine again! Thanks a lot!
