### ISSUE TITLE
invoking file_rec/async is very slow

### ISSUE THREAD

**Issue by eldamir** [Shougo/unite.vim#1083] opened 2015-12-09 08:01 UTC
"The command" = `:Unite -no-split -buffer-name=files -start-insert file_rec/async`

## Problems summary
When I run the command, I see in my status bar instantly, that it is running. after 5+ seconds, the window pops up, and I can start searching. This is way too long to wait. I'm not sure what is causing it. It does not seem to have anything to do with the size of the filetree observed.

## Expected
I'd expect the search window to pop up immediately, and not make the UI unresponsive for several seconds.

## Minimal vimrc
Empty vimrc

## Reproduce

* Install Unite
* Install vimproc
* make vimproc

I installed Unite and vimproc (an have run `make` for vimproc). With no configuration, when I invoke `:Unite -no-split -buffer-name=files -start-insert file_rec/async`, it takes upwards of 5 seconds before the UI is responsive.

**Comment by Shougo** [comment] 2015-12-09 13:13
Unfortunately, unite.vim is slow.  "unite" "vim" "slow" is suggested in Google :worried: 
Because unite.vim is one of most complex plugins and Vim script is very slow than Python(it is not fast language!).

Performance advices:
1.  Upgrade Vim to latest version
2.  unite.vim is slow if the candidates is 10000+.  You should not use it in the huge directories.
3. Enable if_lua feature if you are not in neovim

**Comment by Shougo** [comment] 2015-12-09 13:14
I will rewrite unite.vim for neovim.
It is faster, because it uses the remote plugin feature in neovim.

**Comment by chemzqm** [comment] 2015-12-16 06:01
I've got the same problem the first few days I work with unite
It's turn out ignore_globs options doesn't works for file_rec/async, when I have ignore_globs like this
```
set wildignore+=*/tmp/*,*.so,*~,*.zip,*/.git/*,*/.svn/*,node_modules,*/.DS_Store,coverage,*/*bundle.js,*.map
call unite#custom#source(
  \  'file_rec,file_rec/async,file_mru,file,buffer,grep',
  \  'ignore_globs',
  \  split(&wildignore, ",")
  \ )
```
The command runed by shell would be
```
find -L /Users/chemzqm/component-dev/iscroll -path */.git/* -prune -o -type l -print -o -type f -print 
```
It would not ignore any directory in the `ignore_globs` options except the git dir which looks like always have!

I solved this by using ag command, like this:
```
 let g:unite_source_rec_async_command =
    \ ['ag', '--follow', '--nocolor', '--nogroup',
    \  '--hidden', '-g', '']
```
Since ag understand my gitignore, no unnecessary recursive search is performed, and I can start search immediately with thousands of files even without no cache,

**Comment by chemzqm** [comment] 2015-12-16 06:05
Another problem for file_rec/async is the path would always be absolute path, but I really want to see relative path, so I made a simple patch
``` diff
diff --git a/autoload/unite/sources/rec.vim b/autoload/unite/sources/rec.vim
index b0588a3..5721f0e 100644
--- a/autoload/unite/sources/rec.vim
+++ b/autoload/unite/sources/rec.vim
@@ -251,10 +251,19 @@ let s:source_file_async.name = 'file_rec/async'
 let s:source_file_async.description =
       \ 'asynchronous candidates from directory by recursive'

+function! s:fixPath(path)
+  let cwd = getcwd()
+  let path = substitute(a:path, '^' . getcwd(), '', '')
+  if !len(path) | let path = '.' | endif
+  return path
+endfunction
+
 function! s:source_file_async.gather_candidates(args, context) "{{{
   let paths = s:get_paths(a:args, a:context)
   let a:context.source__directory = join(paths, "\n")

+  let paths = map(paths, 's:fixPath(v:val)')
+
   if !unite#util#has_vimproc()
     call unite#print_source_message(
           \ 'vimproc plugin is not installed.', self.name)
```

**Comment by chemzqm** [comment] 2015-12-16 06:12
I recommend use `ag` as the default search command and prompt user to download it they don't have, since configure the ignore_globs is not easy for both the plugin and user.
A javascript program which uses npm for dependency management could easily have thousands of files under `node_modules` directory, user would suck if the find command search them.

**Comment by Shougo** [comment] 2015-12-18 23:33
@chemzqm "file_rec/git" is my recommended.  It is faster than file_rec/async.

> I recommend use ag as the default search command and prompt user to download it they don't have, since configure the ignore_globs is not easy for both the plugin and user.

I think it is no.
"ag" is not installed in all systems.  And it is faster.  It don't ignore .gitignore though.

**Comment by chemzqm** [comment] 2015-12-19 04:09
@Shougo tks for your response, I've tried to use git command to search files when I was using ctrl-p, the problem is you have to add the new file to git before you want to search it, for people like me using macvim have to switch to the terminal and run `git add`, that feels really bad as I want to focus with my code editor.

`Ag` may not works with all kind of gitignore patterns, but as least it won't recursively search the directory in `~/.gitignore_global`, we just need to create a file `~/.agignore` and add `.git` if we want `ag` to search hidden files but ignore `.git` directory (or use the -t option to search text files while ignore hidden files).

Since the `find` used by `file_rec` could not ignore the directories specified in `ignore_globs`, it could take up `5s` the search files in my repo if it contains `node_modules` folder, on the contrary, `ag` would be done in less than `0.2s`

**Comment by WscriChy** [comment] 2016-02-14 21:53
I have used Unite for couple of last years, I had the same problem with file_rec/async, tries ag, find, ack, very slow, especially if you have HDD, not SSD. I am really grateful to Shougo, but I switched back to [CtrlP](https://github.com/ctrlpvim/ctrlp.vim) and [CtrlP-CMatcher](https://github.com/JazzCore/ctrlp-cmatcher) (to increase the search accuracy). For some reasons it works, much faster, and reliable, at least for file lookups. So basically despite all the feature variety that Unite can offer, I still use more reliable choice. I use CtrlP with find and git ls-files works, find, can switch without restarting vim from one to another.

**Comment by Shougo** [comment] 2016-02-14 23:22
@WscriChy Sorry, for the inconvenience.
Yes, unite.vim is too slow especially in neovim.
I will rewrite it.

**Comment by prabirshrestha** [comment] 2016-02-15 05:14
I would also love to try unite.vim but every time I give a try I keep going back to ctrlp since unite is very slow when the number of files are lot.
@Shougo If you are rewriting unite it would be great if it would also support vim since it now includes job control and channels. Would love to try the early version and give feedback.

**Comment by chemzqm** [comment] 2016-02-15 11:38
Job control is a really great new feature, but we need sometime to wait it implemented.
The main cause of slowness might because vimproc need CursorHold for data output, since the updatetime option in vim is default 4s and some plugin may increase it, the result is waiting period could be too long. After I have `set updatetime=2000` and using `ag` (which respect CVS ignore) I'm satisfied with the performance even searching thousands of files.

CtrlP always cache result by default, that makes it looks faster, but the user have to refresh cache if they need to find file newly created.

**Comment by wsdjeg** [comment] 2016-02-15 11:47
CtrlP also very slow when you recreat cache.

**Comment by WscriChy** [comment] 2016-02-15 18:33
Yes, I know that CtrlP do caching but it is a very rare case when you have to update it, in contrast, to that cases where you just open it and every file is already in a cache. I think this approach would look much better independently of the language (lua, python, viml). Because reloading it every time or in any intervals is really not what you would expect from an editor.

**Comment by prabirshrestha** [comment] 2016-02-15 20:31
@chemzqm has been implemented and even works in windows. https://gist.github.com/prabirshrestha/1c9e884ad13bd83c1ad7 I haven't figured out how to read stdout so using sockets for now.

I guess someone needs to create an api wrapper so that it works in both vim and neovim and fallbacks to python/ruby/vimproc if it doesn't have one yet.

**Comment by Shougo** [comment] 2016-02-15 23:28
https://github.com/Shougo/denite.nvim

This is the my next vaporware!

**Comment by chemzqm** [comment] 2016-02-16 05:25
@prabirshrestha it's channel, according to https://github.com/vim/vim/blob/cbebd4879cc78e670d79b2c57dc33d7b911c962a/runtime/doc/channel.txt
job control is work in progress, but I guess it's coming soon.

**Comment by prabirshrestha** [comment] 2016-02-16 06:34
Yups. That is just channel. 

Here is the job control example that works on windows.

```viml
let job = job_start('cmd /c node hello.js')
let channel = job_getchannel(job)
let output = ch_readraw(channel)
echo output
```

Here was the latest doc that go checked in.
https://github.com/vim/vim/commit/38a55639d603823efcf2d2fdf542dbffdeb60b75

Still lot of api based on the doc are missing which means will have to wait a bit longer for it to get supported.

**Comment by chemzqm** [comment] 2016-02-16 07:41
@prabirshrestha I can confirm that it works on my Mac, but I really need the callback handler,  since I don't want to hack CursorHold event like what I did when using Vimproc.

**Comment by mrbiggfoot** [comment] 2016-02-16 08:05
FWIW - "filelist" feature was implemented specifically to handle this case. I usually work on very large projects (hundreds of thousands of files), so no search is fast enough for me. Using pre-generated file list works really well since the project's FS structure rarely changes. YMMV though.

**Comment by tex** [comment] 2016-02-16 19:28
I too use the 'filelist' feature. It is faster, but the definite solution would be to index the filelist to speed up queries... Something like gtags do for tags or id tool.
Also an action in this source that would update the filelist on background would be nice.

**Comment by WscriChy** [comment] 2016-02-16 22:00
This is a great thing to do a improve something, but I do not think that rewriting it from scratch is such a good idea, since like it was already mentioned and well know that neovim is still under substantial development. That might be better try to port it to an existing vim-python interface piece by piece  and may be enable some neovim api if it is appropriate. Of course it should not a blind port all crutial mentioned during last years drawbacks should be apprehended with new mechanisms, like this one mentioned here. Because even you rewrite it to neovim-job api it will be still slow for some projects and/or consume unwanted computational resources, it is more native to do it through indexing, of course for some people that could be implemented and available as an option. To sum it up, the point is not to start rewriting everything and try to do it in rich-feature manner, but concentrate on some concrete problem and try to solve it locally in already existing implementation.

**Comment by Shougo** [comment] 2016-02-16 22:15
@WscriChy I know your concern.  But I don't think to improve unite sources is the better way.
I had implemented rec/neovim2 sources using neovim remote API.
But it is still slow.  Why?  Because, the most of time consume is Vim and Vim script.
And the current unite implementation is very bad.
I don't want to extend the current implementation.
So I will rewrite it.

I know the neovim API is not stable.
But I know the current implementation well.
I have implemented deoplete asynchronous completion plugin.

**Comment by prabirshrestha** [comment] 2016-02-17 01:21
@chemzqm Callback handler isn't implemented yet. It is coming. At least it didn't work yet when I tried on windows based on the doc.

**Comment by prabirshrestha** [comment] 2016-02-20 04:44
Callback handler is now implemented. Tried this code and it worked in Windows.

Using vim with patch 1362 with +job and +channel.

```viml
function! Handler(channel, message)
    echom a:message
endfunction

let job = job_start('cmd /c dir /s/b c:', { 'callback': 'Handler' })
```

This currently echos all the files and folders recursively in c drive and yet the vim is very responsive when you continue to type. async vim is finally a reality! Now someone needs to create a wrapper so that it uses native vim/neovim and fallbacks to python/ruby threads or use vimproc :)

**Comment by prabirshrestha** [comment] 2016-03-21 05:52
Here is the wrapper library for those of you who are interested in normalizing async job control in vim and neovim.

**Comment by keitee** [comment] 2016-06-29 20:53
Hi all,

Sorry if it's dumb quesiton or I have missed something since I cannot find out what I want from the documentation. I have huge tree which has more than 10k files over networks and am suffering when use file_rec/async. Hence two questions:

1. I know unite builds cache file. When use file_rec/async and there is a cache already created, does unite use that cache files or update caches everytime when run file_rec/async? I expect that unite use cache and returns fast from file_rec/async run but seems slow and to be searching. Is it right assumption?

2. So thought about using cache file as a source and found `file_list` source in unite, #915. However, not sure how to use. Can someone show me some examples please?

Love to stick with unite but this makes me to consider other alternatives.

Many thanks.

**Comment by mrbiggfoot** [comment] 2016-06-29 21:19
2. ```:Unite file_list:my_files```
Where "my_files" is a text file containing file names separated by new line. Works perfectly for my project that has ~9k files.

**Comment by Shougo** [comment] 2016-06-29 23:30
> I know unite builds cache file. When use file_rec/async and there is a cache already created, does unite use that cache files or update caches everytime when run file_rec/async? I expect that unite use cache and returns fast from file_rec/async run but seems slow and to be searching. Is it right assumption?

Please see `g:unite_source_rec_max_cache_files`.
The default value is 20000.  Your file is 10000.  So it is not cached.
And the cache feature does not work for file searching.
To speed up it, you must enable if_lua feature.

**Comment by keitee** [comment] 2016-06-30 08:49
Many thanks @Andrew. That works for me.

Many thanks,
Kit
------
Sorry for a terse reply or typo as sent from a mobile.

2016-06-29 22:19 GMT+01:00 Andrew Pyatkov <notifications@github.com>:

**Comment by keitee** [comment] 2016-06-30 08:51
Thanks Shougo for a reply. Then which source is using the cache feature?

Many thanks,
Kit
------
Sorry for a terse reply or typo as sent from a mobile.

2016-06-30 0:30 GMT+01:00 Shougo <notifications@github.com>:

**Comment by keitee** [comment] 2016-06-30 22:11
To be clear, so caching is only for unite-source-file_rec but not unite-source-file_rec/async? :smile:

**Comment by jalcine** [comment] 2016-06-30 22:49
![](https://link.nylas.com/open/rl00b2nzs55g9gm4myfrbx2t/local-
0c1bfe13-e8f3?r=cmVwbHkrMDAwNmU2MDQwZjg0ZDYyMTRkNDdlNjkzNDczYTg3ZTc4ZmMzY2YyMWZkZjhjYWMzOTJjZjAwMDAwMDAxMTM4ZDViMTM5MmExNjljZTA3MzkxYjQ4QHJlcGx5LmdpdGh1Yi5jb20=)

That should be more clear from the documentation.

  

> To be clear, so caching is only for unite-source-file_rec but not unite-
source-file_rec/async? 😄

>

> —  
> You are receiving this because you are subscribed to this thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/Shougo/unite.vim/issues/1083#issuecomment-229803578&r=cmVwbHkrMDAwNmU2MDQwZjg0ZDYyMTRkNDdlNjkzNDczYTg3ZTc4ZmMzY2YyMWZkZjhjYWMzOTJjZjAwMDAwMDAxMTM4ZDViMTM5MmExNjljZTA3MzkxYjQ4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAbmBC3tBQEI0fUyf6NfGtyRFYjPZV08ks5qRD8TgaJpZM4Gxp_j&r=cmVwbHkrMDAwNmU2MDQwZjg0ZDYyMTRkNDdlNjkzNDczYTg3ZTc4ZmMzY2YyMWZkZjhjYWMzOTJjZjAwMDAwMDAxMTM4ZDViMTM5MmExNjljZTA3MzkxYjQ4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AAbmBPrtNHF-ex1k8qFWfvg1xnyCoRvUks5qRD8TgaJpZM4Gxp_j.gif)

**Comment by Shougo** [comment] 2016-06-30 23:00
> To be clear, so caching is only for unite-source-file_rec but not unite-source-file_rec/async? 

The cache is available in file_rec/async.
But you must change `g:unite_source_rec_max_cache_files` value to enable it on 10000 files.

**Comment by Shougo** [comment] 2016-09-08 16:08
You should use denite.nvim instead.

https://github.com/Shougo/denite.nvim

**Closed by Shougo** 2016-09-08 16:08 UTC
Labels: can't fix, Performance
